src/main/java/de/pach/entities/profile/Address.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.entities.profile;

import java.io.Serializable;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 *
 * @author Christoph Uhlendorff | Patrick Neumüller
 */
@Embeddable
public class Address implements Serializable {

    @NotNull(message = "Postleitzahl darf nicht leer sein")
    @Pattern(regexp = ".*[^0-9].*")
    @Size(min=5, max=5, message = "Muss mindestens 5 und maximal 5 Zeichen lang sein")
    private String zipCode;
    
    @NotNull(message = "Straßenname darf nicht leer sein")
    @Size(min=3, max=20, message = "Muss mindestens 3 und maximal 20 Zeichen lang sein")
    private String streetname;
    
    @NotNull(message = "Hausnummer darf nicht leer sein")
    @Pattern(regexp = ".*[^0-9].*")
    @Size(min=1, max=4, message = "Muss mindestens 1 und maximal 3 Zeichen lang sein")
    private String housenumber;
    
    @NotNull(message = "Stadt darf nicht leer sein")
    @Size(min=3, max=20 , message = "Muss mindestens 3 und maximal 20 Zeichen lang sein")
    private String cityname;
    
    @NotNull(message = "Land darf nicht leer sein")
    @Size(min=3, max=40, message = "Muss mindestens 3 und maximal 40 Zeichen lang sein")
    private String country;

    public Address()
    {
        super();
        zipCode = "00000";
        streetname = "unknown";
        housenumber = "0000";
        cityname = "unknown";
        country = "unknown";
    }
    
    //ToString
    @Override
    public String toString() {
        return "de.pach.entities.profile.Address";
    }

    
    //Getter Setter
    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getStreetname() {
        return streetname;
    }

    public void setStreetname(String streetname) {
        this.streetname = streetname;
    }

    public String getHousenumber() {
        return housenumber;
    }

    public void setHousenumber(String housenumber) {
        this.housenumber = housenumber;
    }

    public String getCityname() {
        return cityname;
    }

    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }  
}

src/main/java/de/pach/entities/profile/EGender.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.entities.profile;

/**
 *
 * @author Christoph Uhlendorff | Patrick Neumüller
 */
public enum EGender {
    
    MALE,
    FEMALE,
    UNKOWN
    
    
}

src/main/java/de/pach/entities/profile/ETitle.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.entities.profile;

/**
 *
 * @author Christoph Uhlendorff | Patrick Neumüller
 */
public enum ETitle {
    
    DR,
    PROF,
    DRPROF,
    NOTHING

}

src/main/java/de/pach/entities/profile/UserLogin.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.entities.profile;

import de.pach.entities.EntityWithId;
import java.io.Serializable;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.util.Arrays;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

/**
 *
 * @author Christoph Uhlendorff | Patrick Neumüller
 */
@Entity
public class UserLogin extends EntityWithId implements Serializable {

    private byte[] salt;
    private byte [] password;
    
    public UserLogin()
    {
        super();
        salt = null;
        password = null;
    }
    
    /*
    * regex fuer email verifizierung 
    * @see https://docs.oracle.com/cd/E19798-01/821-1841/gkahq/index.html
    */
    @NotNull(message = "Email darf nicht leer sein")
    @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\."
        +"[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@"
        +"(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?",
             message="{invalid.email}")
    private String email;
    
    // TODO Password Hash 
    public byte[] hashPassword( String password ) {
        int iterations = 10000;
        int keyLength = 128;
        
       try {
           SecretKeyFactory skf = SecretKeyFactory.getInstance( "PBKDF2WithHmacSHA512" );
           PBEKeySpec spec = new PBEKeySpec( password.toCharArray(), getSalt(), iterations, keyLength );
           SecretKey key = skf.generateSecret( spec );
           byte[] res = key.getEncoded( );
           return res;
       } catch( NoSuchAlgorithmException | InvalidKeySpecException e ) {
           throw new RuntimeException( e );
       }
   }
    

    
    //Getter Setter
    private byte [] getSalt()
    {
        if(salt == null || salt.length != 20){
        SecureRandom random = new SecureRandom();
        salt = new byte[20];
        random.nextBytes(salt);
        }
        return salt;
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public byte[] getPassword() {
        return password;
    }

    public boolean loginCorrect(String password)
    {
      return Arrays.equals(hashPassword(password), this.password);     
    }
    
    public void setPassword(String password) {
        this.password = hashPassword(password);
    }
}

src/main/java/de/pach/models/DoctorOverviewModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.models;

import de.pach.controller.UserController;
import de.pach.entities.roles.AbstractUser;
import de.pach.entities.roles.Doctor;
import de.pach.entities.roles.Patient;
import de.pach.repositories.UserRepo;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.PrimeFaces;
import org.primefaces.event.SelectEvent;

/**
 *
 * @author chriss
 */
@Named
@SessionScoped
public class DoctorOverviewModel implements Serializable {

    @Inject
    LoginSessionWrapper session;

    @Inject
    UserRepo userRepo;
    
    @Inject
    UserController userController;

    private List<Doctor> doctors;

    public List<Doctor> getDoctors() {
        return doctors;
    }

    public void setDoctors(List<Doctor> doctors) {
        this.doctors = doctors;
    }

    public List<Doctor> getFilteredDoctors() {
        return filteredDoctors;
    }

    public void setFilteredDoctors(List<Doctor> filteredDoctors) {
        this.filteredDoctors = filteredDoctors;
    }
    private List<Doctor> filteredDoctors;
    
    @PostConstruct
    public void init()
    {
        doctors = userRepo.getAll(Doctor.class);
    }
    
    public List<Doctor> getPatientsDoctors() {
        return ((Patient) session.getLogin().getUser()).getAllowedDoctors();
    }

    public void removeDoctor(Doctor d) {
        ((Patient) session.getLogin().getUser()).removeAllowedDoctor(d);
        AbstractUser p = userController.updateUser(session.getLogin().getUser());
        session.getLogin().setUser(p);
    }

    public void showAddDoctorDialog() {
        Map<String, Object> options = new HashMap<String, Object>();
        options.put("resizable", false);
        options.put("draggable", false);
        options.put("modal", true);
        PrimeFaces.current().dialog().openDynamic("/patient/dialog/SelectDoctor", options, null);
    }

    public void onDoctorChosen(SelectEvent event) {
        Doctor doctor = (Doctor) event.getObject();
        ((Patient) session.getLogin().getUser()).addAllowedDoctor(doctor);
        AbstractUser p = userController.updateUser(session.getLogin().getUser());
        session.getLogin().setUser(p);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Doktor hinzugefügt", doctor.getUserProfile().getLastname() + ", " + doctor.getUserProfile().getName());
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
    
    public void selectDoctorFromDialog(Doctor d)
    {
        PrimeFaces.current().dialog().closeDynamic(d);
    }
}

src/main/java/de/pach/models/RegisterModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.pach.models;

import de.pach.controller.RegisterController;
import de.pach.entities.profile.Address;
import de.pach.entities.profile.EGender;
import de.pach.entities.profile.ETitle;
import de.pach.entities.profile.Profile;
import de.pach.entities.profile.UserLogin;
import de.pach.entities.roles.AbstractUser;
import de.pach.entities.roles.Doctor;
import de.pach.entities.roles.Patient;
import de.pach.entities.vaccinate.Impfpass;
import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.event.FlowEvent;

/**
 *
 * @author chriss
 */

@Named
@SessionScoped
public class RegisterModel implements Serializable {
    
    private AbstractUser user;
    private Profile userProfile;
    
    private String newPassword = "";
    private String newPasswordAgain = "";
    
    
    
    @Inject
    RegisterController registerController;

    private boolean skip;

    public boolean isSkip() {
        return skip;
    }

    public void save() {
        finalizeRegistration();
        FacesMessage msg = new FacesMessage("Erfolgreich", "Willkommen: " + user.getUserProfile().getName());
        FacesContext.getCurrentInstance().addMessage("", msg);
    }

    public enum Usertype {
        PATIENT, DOCTOR
    };

    private Usertype usertype;

    @PostConstruct
    void init() {
        userProfile = new Profile();
        userProfile.setUserLogin(new UserLogin());
        userProfile.setAddress(new Address());
        usertype = Usertype.PATIENT;

        //Clear Profil
        userProfile.getAddress().setCityname("");
        userProfile.getAddress().setCountry("");
        userProfile.getAddress().setHousenumber("");
        userProfile.getAddress().setZipCode("");
        userProfile.getAddress().setStreetname("");

        userProfile.setLastname("");
        userProfile.setName(null);
        userProfile.setBirthday(LocalDate.now());
    }

    //---------------------------
    //  Profile
    //---------------------------
    public void setUsertype(Usertype usertype) {
        this.usertype = usertype;
    }

    public Usertype getUsertype() {
        return usertype;
    }

    public void setUsername(String username) {
        userProfile.setName(username);
    }

    public String getUsername() {
        return userProfile.getName();
    }

    public void setLastname(String lastname) {
        userProfile.setLastname(lastname);
    }

    public String getLastname() {
        return userProfile.getLastname();
    }

    public void setTitle(ETitle title) {
        userProfile.setTitle(title);
    }

    public ETitle getTitle() {
        return userProfile.getTitle();
    }

    public void setGender(EGender gender) {
        userProfile.setGender(gender);
    }

    public EGender getGender() {
        return userProfile.getGender();
    }

    //---------------------------
    //  Login
    //---------------------------
    public void setEmail(String email) {
        userProfile.getUserLogin().setEmail(email);
    }

    public String getEmail() {
        return userProfile.getUserLogin().getEmail();
    }

    public void setBirthday(LocalDate date) {
        userProfile.setBirthday(date);
    }

    public LocalDate getBirthday() {
        return userProfile.getBirthday();
    }

    public void setPassword(String password) {
        userProfile.getUserLogin().setPassword(password);
    }

    //---------------------------
    //  Address
    //---------------------------
    public void setStreetname(String streetname) {
        userProfile.getAddress().setStreetname(streetname);
    }

    public String getStreetname() {
        return userProfile.getAddress().getStreetname();
    }

    public void setHousenumber(String housenumber) {
        userProfile.getAddress().setHousenumber(housenumber);
    }

    public String getHousenumber() {
        return userProfile.getAddress().getHousenumber();
    }

    public void setCityName(String cityName) {
        userProfile.getAddress().setCityname(cityName);
    }

    public String getCityName() {
        return userProfile.getAddress().getCityname();
    }

    public void setZipcode(String zipcode) {
        userProfile.getAddress().setZipCode(zipcode);
    }

    public String getZipcode() {
        return userProfile.getAddress().getZipCode();
    }

    public void setCountry(String country) {
        userProfile.getAddress().setCountry(country);
    }

    public String getCountry() {
        return userProfile.getAddress().getCountry();
    }

    //---------------------------
    //---------------------------
    public void finalizeRegistration() {
        
        if (null == usertype) {
            throw new NullPointerException("Usertype is null");
        } else {
            switch (usertype) {
                case PATIENT:
                    user = new Patient();
                    ((Patient) user).setUserImpfpass(new Impfpass());
                    break;
                case DOCTOR:
                    user = new Doctor();
                    break;
                default:
                    throw new IllegalArgumentException("UserRole " + usertype.toString() + " is not a valid Role.");
            }
        }
        
        userProfile.getUserLogin().setPassword(newPassword);
        
        userProfile.setVerified(true);
        user.setUserProfile(userProfile);
        
        registerController.finishRegistration(user);
    }

    public boolean validateUser(String s_uuid) {
        UUID uuid = UUID.fromString(s_uuid);
        return registerController.verifyUser(uuid);
    }

    public String onFlowProcess(FlowEvent event) {
        if (skip) {
            skip = false;
            return "confirm";
        } else {
            return event.getNewStep();
        }
    }

    //Gender
    public Object[] getGenders() {
        SelectItem[] items = new SelectItem[EGender.values().length];
        for (int i = 0; i < items.length; i++) {

            items[i] = new SelectItem(EGender.values()[i], EGender.values()[i]
                    .toString().toLowerCase());

        }
        return items;
    }

    //Title
    public Object[] getTitles() {
        SelectItem[] items = new SelectItem[ETitle.values().length];
        for (int i = 0; i < items.length; i++) {

            items[i] = new SelectItem(ETitle.values()[i], ETitle.values()[i]
                    .toString().toLowerCase());

        }
        return items;
    }

    //Usertype
    public Object[] getUsertypes() {
        SelectItem[] items = new SelectItem[Usertype.values().length];
        for (int i = 0; i < items.length; i++) {

            items[i] = new SelectItem(Usertype.values()[i], Usertype.values()[i]
                    .toString().toLowerCase());

        }
        return items;
    }
    
    public void addMessage(String summary, FacesMessage.Severity serverity) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, null);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
    
    //SetPassword
    public void checkPassword() {
        if (newPassword.equals("") || newPassword.equals("") || newPasswordAgain.equals("")) {
            
            addMessage("Bitte alle Felder ausfüllen", FacesMessage.SEVERITY_ERROR);
            return;
        }

        if (!newPassword.equals(newPasswordAgain)) {
            addMessage("Die Passwörter stimmen nicht überein", FacesMessage.SEVERITY_ERROR);
            return;

        }
        
        if(newPassword.equals(newPasswordAgain)){
            addMessage("Passwörter passen!", FacesMessage.SEVERITY_INFO);
            setPassword(newPassword);
            
        }
        
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getNewPasswordAgain() {
        return newPasswordAgain;
    }

    public void setNewPasswordAgain(String newPasswordAgain) {
        this.newPasswordAgain = newPasswordAgain;
    }
    

}

src/main/webapp/patient/DoctorOverview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Impfpass</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"></link>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="sidebar.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="navbar.css"></h:outputStylesheet>

        <div class="topnav">
            <label id="logo">DigitalerImpfpass</label>
            <a class="active" href="#home">Home</a>
            <a href="#news">News</a>
            <a href="#contact">Contact</a>
            <a href="#about">About</a>
        </div>
        <div class="navbar-spacer"></div>

        <!-- Sidebar -->
        <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:250px;">
            <h3 class="w3-bar-item">Menu</h3>
            <h:form>          
                <p:growl id="messages" showDetail="true" />
                <p:menu toggleable="true" style="margin: 10px; border-style: none; border-radius: 0;">
                    <p:submenu label="Übersicht">
                        <p:menuitem value="Start" outcome="/patient/DueVaccinations" icon="ui-icon-disk" />
                        <p:menuitem value="Profil" outcome="/patient/profile" icon="ui-icon-disk" />
                        <p:menuitem value="Impfungen" outcome="/patient/impfpass" icon="ui-icon-disk"/>
                        <p:menuitem value="Doktoren" outcome="/patient/DoctorOverview" icon="ui-icon-disk" />
                    </p:submenu>
                </p:menu>
            </h:form>
        </div>

        <!-- Page Content -->
        <div id="pageContent" style="margin-left:250px">

            <div class="w3-container w3-teal">
                <h1>Ihre Doktoren</h1>
                <h:form>
                    <p:growl id="growl" showDetail="true" />
                    <p:commandButton style="margin-bottom: 15px;" value="Doktor hinzufügen" icon="ui-icon-extlink" actionListener="#{doctorOverviewModel.showAddDoctorDialog()}">
                        <p:ajax event="dialogReturn" listener="#{doctorOverviewModel.onDoctorChosen}" update="growl docOverview" />
                    </p:commandButton>
                </h:form>
            </div>

            <h:form id="docOverview">
                <p:growl id="message" showDetail="true" />
                <p:dataList emptyMessage="Der Impfpass wurde mit keinem Doktor geteilt." value="#{doctorOverviewModel.patientsDoctors}" var="doctor" type="ordered" itemType="none" paginator="true" rows="10" styleClass="paginated">
                    <p:commandButton icon="fa fa-fw fa-remove" actionListener="#{doctorOverviewModel.removeDoctor(doctor)}"  update="docOverview">
                        <p:confirm header="Wirklich entfernen?" message="Soll der Doktor wirklich aus der Liste gelöscht werden?" icon="ui-icon-alert" />
                    </p:commandButton>
                    <h:outputText value="#{doctor.userProfile.lastname}, #{doctor.userProfile.name}" style="display:inline-block"/>
                </p:dataList>

                <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                    <p:commandButton value="Ja" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                    <p:commandButton value="Nein" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                </p:confirmDialog>
            </h:form>
        </div>
    </h:body>
</html>

src/main/webapp/patient/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Profil</title>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"></link>
    </h:head>
    <h:body>
        <h:outputStylesheet library="css" name="sidebar.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="navbar.css"></h:outputStylesheet>

        <div class="topnav">
            <label id="logo">DigitalerImpfpass</label>
            <a class="active" href="#home">Home</a>
            <a href="#news">News</a>
            <a href="#contact">Contact</a>
            <a href="#about">About</a>
        </div>
        <div class="navbar-spacer"></div>

        <!-- Sidebar -->
        <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:250px;">
            <h3 class="w3-bar-item">Menu</h3>
            <h:form>          
                <p:growl id="messages" showDetail="true" />
                <p:menu toggleable="true" style="margin: 10px; border-style: none; border-radius: 0;">
                    <p:submenu label="Übersicht">
                        <p:menuitem value="Start" outcome="/patient/DueVaccinations" icon="ui-icon-disk" />
                        <p:menuitem value="Profil" outcome="/patient/profile" icon="ui-icon-disk" />
                        <p:menuitem value="Impfungen" outcome="/patient/impfpass" icon="ui-icon-disk"/>
                        <p:menuitem value="Doktoren" outcome="/patient/DoctorOverview" icon="ui-icon-disk" />
                    </p:submenu>
                </p:menu>
            </h:form>
        </div>

        <!-- Page Content -->
        <div style="margin-left:250px">

            <div class="w3-container w3-teal">
                <h1>Profil</h1>
            </div>

            <div class="ui-fluid">
                <div class="w3-container w3-teal">
                    <h3>Allgemein</h3>
                </div>
                <h:form>
                    <p:panelGrid columns="2" id="general_change_grid" columnClasses="ui-grid-col-2,ui-grid-col-10" layout="grid" styleClass="ui-panelgrid-blank">
                        <p:growl id="general_messages" showDetail="true" />
                        <p:spacer/>

                        <p:outputLabel for="gender" value="Geschlecht"/>
                        <p:selectOneMenu value="#{userProfileModel.gender}" id="gender">
                            <f:selectItems value="#{userProfileModel.genders}" />
                        </p:selectOneMenu>

                        <p:outputLabel for="title" value="Titel"/>
                        <p:selectOneMenu value="#{userProfileModel.title}" id="title">
                            <f:selectItems value="#{userProfileModel.titles}" />
                        </p:selectOneMenu>

                        <h:outputText value="Vorname: *" />
                        <p:inputText id="username" value="#{userProfileModel.username}" required="true"
                                     label="Vorname" validatorMessage="Vorname ist nicht gültig">
                            <f:validateLength minimum="1" maximum="20" />
                        </p:inputText>

                        <h:outputText value="Nachname: *" />
                        <p:inputText id="nachname" value="#{userProfileModel.lastname}" required="true" label="Nachname"
                                     validatorMessage="Nachname ist nicht gültig">
                            <f:validateLength minimum="1" maximum="20" />
                        </p:inputText>

                        <h:outputText value="Email: *" />
                        <p:inputText id="email" value="#{userProfileModel.email}" required="true" label="Email" validatorMessage="Email ist nicht gültig">
                            <f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
                        </p:inputText>

                        <!--p:outputLabel for="calendar" value="Calendar"/-->
                        <!--p:calendar value="{userProfileModel.birthdate}" id="calendar"/-->
                        <p:spacer/>
                        <p:commandButton id="confirm_change_general" update="general_change_grid" actionListener="#{userProfileModel.changeGeneral}" value="Speichern" icon="fa fa-edit"/>
                    </p:panelGrid>
                </h:form>
                <br></br>
                <div class="w3-container w3-teal">
                    <h3>Angaben ändern</h3>
                </div>
                <h:form>
                    <p:panelGrid columns="2" id="pw_change_grid" columnClasses="ui-grid-col-2,ui-grid-col-10" layout="grid" styleClass="ui-panelgrid-blank">
                        <p:growl id="pw_messages" showDetail="true" />
                        <p:spacer/>

                        <p:outputLabel for="pwd" value="Aktuelles Passwort"/>
                        <p:password id="pwd" value="#{userProfileModel.currentPassword}" validatorMessage="Passwort Fehler">
                            <f:validateLength minimum="3" maximum="20" />
                        </p:password>

                        <p:outputLabel for="pwd_new" value="Neues Passwort"/>
                        <p:password id="pwd_new" value="#{userProfileModel.newPassword}" required="true" validatorMessage="Passwort Fehler">
                            <f:validateLength minimum="3" maximum="20" />
                        </p:password>

                        <p:outputLabel for="pwd_new_repeat" value="Neues Passwort wiederholen"/>
                        <p:password id="pwd_new_repeat" value="#{userProfileModel.newPasswordRepeat}" required="true" validatorMessage="Passwort Fehler">
                            <f:validateLength minimum="3" maximum="20" />
                        </p:password>

                        <p:spacer/>
                        <p:commandButton id="confirm_change_pwd" update="pw_change_grid" actionListener="#{userProfileModel.changePassword}" value="Passwort ändern" icon="fa fa-edit"/>
                    </p:panelGrid>
                </h:form>
                <br></br>
                <div class="w3-container w3-teal">
                    <h3>Adresse ändern</h3>
                </div>
                <h:form>
                    <p:panelGrid columns="2" id="address_change_grid" columnClasses="ui-grid-col-2,ui-grid-col-10" layout="grid" styleClass="ui-panelgrid-blank">
                        <p:growl id="address_messages" showDetail="true" />
                        <p:spacer/>

                        <h:outputText value="Straßenname " />
                        <p:inputText id="strasse" value="#{userProfileModel.streetname}" required="true" validatorMessage="Straßenname ist nicht gültig">
                            <f:validateLength minimum="1" maximum="20" />
                        </p:inputText>

                        <h:outputText value="Hausnummer: " />
                        <p:inputText id="hausnummer" value="#{userProfileModel.housenumber}" required="true" validatorMessage="Hausnummer ist nicht gültig">
                            <f:validateDoubleRange minimum="1" maximum="9999" />
                        </p:inputText>

                        <h:outputText value="Stadt: " />
                        <p:inputText id="stadt" value="#{userProfileModel.cityName}" required="true" validatorMessage="Stadt ist nicht gültig">
                            <f:validateLength minimum="1" />
                        </p:inputText>

                        <h:outputText value="PLZ: " />
                        <p:inputText id="plz" value="#{userProfileModel.zipcode}" required="true" validatorMessage="PLZ ist nicht gültig" >
                            <f:validateDoubleRange minimum="10000" maximum="99999" />
                        </p:inputText>

                        <h:outputText value="Land: " />
                        <p:inputText id="land" value="#{userProfileModel.country}" required="true" validatorMessage="Land ist nicht gültig">
                            <f:validateLength minimum="1" />
                        </p:inputText>
                        <p:spacer/>
                        
                        <p:commandButton id="confirm_change_address" update="address_change_grid" actionListener="#{userProfileModel.changeAddress}" value="Speichern" icon="fa fa-edit"/>
                    </p:panelGrid>
                </h:form>
            </div>
        </div>
    </h:body>
</html>